### ISSUE TITLE
Uknown css

### ISSUE THREAD

**Issue by brianteeman** [lucid-fox/social-magick#19]
The class text-decoration-underline is not present in the default joomla 3 admin template

https://github.com/lucid-fox/social-magick/blob/3e8b4f2757f735365c3edc071dc44e9d188d7e27/language/en-GB/en-GB.plg_system_socialmagick.ini#L5

**Comment by brianteeman** [comment]
Included in PR #20

**Comment by nikosdion** [comment]
Hello Brian,

In case you missed it on the README and the Releases page, this plugin is compatible with BOTH Joomla 3 AND Joomla 4.

As you are already aware, Joomla  (in fact Mambo) made the decision that plugin options are hardcoded in its XML manifest file circa 2003. This means that barring the release of two separate extensions for Joomla 3 and 4 there is no way to separate the options and the language strings to be used in each version of Joomla.

Furthermore, Joomla has made it so you cannot present custom messages in the XML forms used for plugin, module, component and template options except for the notes field. The notes field requires hardcoded HTML in the language strings. Combined with the above it means that we need to set up our language strings in a way that they will both display correctly on both Joomla 3 and 4.

As a result this issue is invalid because it would remove support for Joomla 4.
