### ISSUE TITLE
1. Add an Option to the "Open Graph Description": "first X characters of the article" | 2. allow to choose a Default "Extra image source"

### ISSUE THREAD

**Issue by woluweb** [lucid-fox/social-magick#30]
Beta3 introduced very nice & useful "default" options to Social Magick.
This is great bc it avoids having to necessarily configure each and every menu item.

Two suggestions to improve it further if I may:

1.

For "Open Graph Description" there are already 3 options
- No
- User Joomla's Meta Description
- Custom

I would propose to add a fourth : 
- first X characters of the article

(well the "first X characters of the stripped article or category" to be more precise)

2.

For the "Extra image source", it would be useful to have an extra parameter to have a default value at the Plugin level
(this way users would for ex. be able to choose "intro image" by default by leaving the setting on "inherit" at the Menu-item level)

**Comment by nikosdion** [comment]
Regarding the first suggestion, I'd say no. This is equivalent to using "No". This is exactly social media will do in the absence of a description (OpenGraph and meta). Moreover, they _could_ trim the text to different lengths depending on the medium and channel your article is displayed in. Why reinvent the wheel and make it less round?

Regarding the second suggestion, you can have a default at the category level. This makes far more sense than a global default. If you really want a global default there's a standard Joomla way to do it. Create a root category which itself has no articles and batch process all of your existing top level categories, moving them into it. Now your root category can be assigned default options and they can be overridden in each child category. Still, this is a bit icky and likely to catch you by surprise. It's best to spend 5' to set up the default per category than waste a day trying to figure out where the bloody image is coming from six months after delivering a site.

**Comment by woluweb** [comment]
1. "open graph description"

Oh I had not realized that setting it to "No" was coming to the same. Good then.
But testing this right now, even if I set to No globally and/or at the Menu item and/or at the Article level, both the Facebook Debugger or metatags.io still uses the Site Meta Description as Description (definitely not the beginning of the article).
Have I missed something? Some other parameter in Social Magick or in Joomla?

2. default "extra image source"

Oh excellent. I had not thought it could be set at the Category level.
Then indeed it is good enough (I wanted to avoid having to do it for each and every menu item).

---
Txs again for the feedback.
Normally I would read the Manual :D But since there is none I try and discover as much as I can by myself.

Anyway, beta3 makes Social Magick so much more powerful with all those Default options!

**Comment by nikosdion** [comment]
Regarding the first one, I said
> This is exactly social media will do in the absence of a description (OpenGraph and meta). 
Social media typically uses the following information, in this order: opengraph tags, meta description, microdata, trying to figure out a preview by itself (typically a truncated excerpt of your site). If you've set up a meta description then you already have an excellent source of a description for social media! Trying to use a confusing auto-truncated version of your first paragraph is self-defeating.

Regarding the manual, yeah, @crystalenka is already on it. Writing the [Template Options documentation page](https://github.com/lucid-fox/social-magick/wiki/Template-Options) took forever because of the need to demonstrate how it all affects the visible outcome and then we ran out of time as there was paid work to be done by both of us :p Hopefully we'll get back to documenting things this week.
